let id_not    = Id.make "not"
let id_neg    = Id.make "neg"
let id_add    = Id.make "+"
let id_sub    = Id.make "-"
let id_mul    = Id.make "*"
let id_div    = Id.make "/"
let id_mod    = Id.make "%"
let id_eq     = Id.make "=="
let id_ne     = Id.make "!="
let id_lt     = Id.make "<"
let id_gt     = Id.make ">"
let id_le     = Id.make "<="
let id_ge     = Id.make ">="
let id_concat = Id.make "^"
let id_nil    = Id.make "Nil"
let id_cons   = Id.make "Cons"

let op_not    = S.Var id_not
let op_neg    = S.Var id_neg
let op_add    = S.Var id_add
let op_sub    = S.Var id_sub
let op_mul    = S.Var id_mul
let op_div    = S.Var id_div
let op_mod    = S.Var id_mod
let op_eq     = S.Var id_eq
let op_ne     = S.Var id_ne
let op_lt     = S.Var id_lt
let op_gt     = S.Var id_gt
let op_le     = S.Var id_le
let op_ge     = S.Var id_ge
let op_concat = S.Var id_concat
